name: CBMPA PAE Auto-Updater

on:
  workflow_dispatch:   # permite rodar manualmente
  schedule:
    - cron: "0 */2 * * *"  # a cada 2 horas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          PAE_CPF: ${{ secrets.PAE_CPF }}
          PAE_SENHA: ${{ secrets.PAE_SENHA }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TAB_NAME: ${{ secrets.SHEET_TAB_NAME }}
          SHEET_GID: ${{ secrets.SHEET_GID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          HEADLESS: "true"
          LOG_LEVEL: "INFO"
        run: |
          python run.py
